
############################ Battery Automations, Scripts & Sensors ##################################
# All entities to have the prefix: "battery_" or name: Battery: 
######################################################################################################

# Table of Contents
#   Automations
#     Time to charge John's Phone
#     Time to charge Irina's Phone
#     Turn ON Bosch Battery Charger
#     Turn OFF Bosch Battery Charger

automation:
  # Time to charge John's Phone
  - id: battery_time_to_charge_johns_phone
    alias: 'Battery: Time to charge John''s Phone '
    description: ''
    trigger:
    - below: '30'
      entity_id: sensor.pixel_3a_battery
      platform: numeric_state
    condition: []
    action:
    - alias: ''
      data:
        message: Time to charge your phone. Place it in the desk charger.
      service: notify.mobile_app_pixel_3a
#    - data: {}
#      entity_id: switch.s6_desk_charger
#      service: switch.turn_on     

  # Time to charge Irina's Phone
  - id: battery_time_to_charge_irinas_phone
    alias: 'Battery: Time to charge Irina''s Phone'
    description: ''
    trigger:
    - below: '20'
      entity_id: sensor.lenovo_p2_battery
      platform: numeric_state
    condition: []
    action:
    - data:
        message: Charge Irina''s Phone!
      service: notify.mobile_app_pixel_3a
    - data:
        message: Домашний помощник предлагает зарядить телефон!
      service: notify.mobile_app_lenovo_p2a42
    - data:
        entity_id: media_player.lounge_assistant
        message: 'Time to charge Irinas phone!'
      service: tts.google_say

  # Turn ON Bosch Battery Charger
  - id: battery_turn_on_bosch_battery_charger
    alias: 'Battery: Turn ON Bosch Battery Charger'
    description: ''
    trigger:
    - at: "11:00:00"
      platform: time
    condition: 
      condition: time
      weekday: fri
    action:
    - data: {}
      entity_id: switch.s2_bosch_battery_charger
      service: switch.turn_on
  
  # Turn OFF Bosch Battery Charger
  - id: battery_turn_off_bosch_battery_charger
    alias: 'Battery: Turn OFF Bosch Battery Charger'
    description: ''
    trigger:
    - at: "12:00:00"
      platform: time
    action:
    - data: {}
      entity_id: switch.s2_bosch_battery_charger
      service: switch.turn_off     
