
############################ Harmony Remote Automations, Scripts & Sensors ############################ 
# See https://www.home-assistant.io/integrations/harmony
# All entities to have the prefix: "harmony_" or name: "Harmony:"
# 
# Table of Contents
#   Sensors
#     Harmony Lounge Activity
#     Harmony Bedroom Activity
#     Harmony Kitchen Activity
#
#   Switches
#     Lounge TV
#     Lounge BluRay
#     Lounge iPlayer
#     Lounge Audio Cast
#     Bedroom TV
#     Bedroom Audio Cast
#     Bedroom YouView
#     Kitchen Audio Cast
#
#  Scripts
#    Lounge Volume Plus (Up)
#    Lounge Volume Minus (Down)
#    Lounge Mute#
#    Kitchen Volume Plus (Up)
#    Kitchen Volume Minus (Down)
#    Bedroom Volume Plus (Up)
#    Bedroom Minus (Down)
#
#  Automations
#    Freesat TV inputs on Amp & Samsung TV after delay
#    iPlayer inputs on Amp & Samsung TV after delay
#    BluRay inputs on Amp & Samsung TV after delay
#    Lounge Cast input on Amp after delay
#    Switch off Amplifier
#    Change to HDMI2 input when switching from TV or iPlayer to BluRay
#    Change to HDMI2 input when switching from TV or iPlayer to BluRay with repeat as TV will be off
#    Change to HDMI3 input when switching BluRay or iPlayer to TV
#    Change to HDMI1 input when switching from TV or BluRay to iPlayer
#    Change to HDMI1 input when switching from Audio to iPlayer with delay as TV needs to turn on
#
#  Conf files:
#    Harmony Lounge: harmony_5710153.conf
#    Harmony Bedroom: harmony_16100813.conf
#    Harmony Kitchen: harmony_16111082.conf

############################ Harmony Sensors ############################ 
sensor:
  - platform: template
    sensors:
      harmony_lounge_activity:
        friendly_name: 'Harmony Lounge Activity'
        value_template: >-
          {{ state_attr("remote.harmony_lounge", "current_activity") }}
        icon_template: mdi:remote
      harmony_bedroom_activity:
        friendly_name: 'Harmony Bedroom Activity'
        value_template: >-
          {{ state_attr("remote.harmony_bedroom", "current_activity") }}
        icon_template: mdi:remote
      harmony_kitchen_activity:
        friendly_name: 'Harmony Kitchen Activity'
        value_template: >-
          {{ state_attr("remote.harmony_kitchen", "current_activity") }}
        icon_template: mdi:remote

############################ Harmony Switches ############################ 
switch:
- platform: template
  switches:
    # Lounge TV
    harmony_lounge_tv:
      friendly_name: Harmony Lounge TV
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'TV') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_lounge
          activity: TV
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_lounge
          activity: TV
      icon_template: >-
          {% if is_state('switch.harmony_lounge_tv', 'on') %}
            mdi:television-classic
          {% else %}
            mdi:television-classic-off
          {% endif %}          

    # Lounge BluRay
    harmony_lounge_bluray:
      friendly_name: Harmony Lounge BluRay
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'BluRay') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_lounge
          activity: BluRay
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_lounge
          activity: BluRay
      icon_template: mdi:disc-player
      
    # Lounge iPlayer
    harmony_lounge_iplayer:
      friendly_name: Harmony Lounge iPlayer
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'iPlayer') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_lounge
          activity: iPlayer
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_lounge
          activity: iPlayer
      icon_template: >-
          {% if is_state('switch.harmony_lounge_iplayer', 'on') %}
            mdi:television-play
          {% else %}
            mdi:television-off
          {% endif %}

    # Lounge Audio Cast
    harmony_lounge_cast:
      friendly_name: Harmony Lounge Cast
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'Lounge Cast') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_lounge
          activity: 'Lounge Cast'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_lounge
          activity: 'Lounge Cast'
      icon_template: >-
          {% if is_state('switch.harmony_lounge_cast', 'on') %}
            mdi:cast-audio
          {% else %}
            mdi:speaker-off
          {% endif %}
          
          
    # Bedroom TV
    harmony_bedroom_tv:
      friendly_name: Bedroom TV
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'Bedroom TV') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_bedroom
          activity: Bedroom TV
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_bedroom
          activity: Bedroom TV
      icon_template: >-
          {% if is_state('switch.harmony_bedroom_tv', 'on') %}
            mdi:television-classic
          {% else %}
            mdi:television-classic-off
          {% endif %}
          
   # Bedroom YouView
    harmony_bedroom_youview:
      friendly_name: Harmony Bedroom YouView
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'YouView') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_bedroom
          activity: YouView
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_bedroom
          activity: YouView
      icon_template: >-
          {% if is_state('switch.harmony_bedroom_youview', 'on') %}
            mdi:television-classic
          {% else %}
            mdi:television-classic-off
          {% endif %}
          
   # Bedroom Netflix
    harmony_bedroom_netflix:
      friendly_name: Harmony Bedroom Netflix
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'Netflix') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_bedroom
          activity: Netflix
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_bedroom
          activity: Netflix
      icon_template: >-
          {% if is_state('switch.harmony_bedroom_netflix', 'on') %}
            mdi:television-play
          {% else %}
            mdi:television-off
          {% endif %}      
                    
    # Bedroom Audio Cast
    harmony_bedroom_audio_cast:
      friendly_name: Bedroom Audio Cast
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'Bedroom Cast') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_bedroom
          activity: Bedroom Cast
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_bedroom
          activity: Bedroom Cast
      icon_template: >-
          {% if is_state('switch.harmony_bedroom_audio_cast', 'on') %}
            mdi:cast-audio
          {% else %}
            mdi:speaker-off
          {% endif %}    

    # Kitchen Audio Cast
    harmony_kitchen_audio_cast:
      friendly_name: Kitchen Audio Cast
      value_template: >-
        {{ is_state_attr('remote.harmony_kitchen', 'current_activity', 'Kitchen Cast') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_kitchen
          activity: Kitchen Cast
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_kitchen
          activity: Kitchen Cast
      icon_template: >-
          {% if is_state('switch.harmony_kitchen_audio_cast', 'on') %}
            mdi:cast-audio
          {% else %}
            mdi:speaker-off
          {% endif %}    
 
############################ Harmony Scripts ############################        
# Scripts
#########################################################################
script:
  #######################################################################
  # Volume Control Scripts - Lounge
  #######################################################################
  # Lounge Volume Plus (Up)
  harmony_volume_plus:
    alias: 'Harmony: Volume Plus'
    sequence:
    - data:
        command:
        - VolumeUp
        device: Audiolab CDQ
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  # Lounge Volume Minus (Down)
  harmony_volume_minus:
    alias: 'Harmony: Volume Minus'
    sequence:
    - data:
        command:
        - VolumeDown
        device: Audiolab CDQ
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  # Lounge Mute
  harmony_volume_mute:
    alias: 'Harmony: Volume Mute'
    sequence:
    - data:
        command:
        - Mute
        device: Audiolab CDQ
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  #######################################################################
  # Volume Control Scripts - Kitchen
  #######################################################################
  
  # Kitchen Volume Plus (Up)
  harmony_kitchen_volume_plus:
    alias: 'Harmony: Kitchen Volume Plus'
    sequence:
    - data:
        command:
        - VolumeUp
        device: Project Audio Systems Amp
      entity_id: remote.harmony_kitchen
      service: remote.send_command
  # Kitchen Volume Minus (Down)
  harmony_kitchen_volume_minus:
    alias: 'Harmony: Kitchen Volume Minus'
    sequence:
    - data:
        command:
        - VolumeDown
        device: Project Audio Systems Amp
      entity_id: remote.harmony_kitchen
      service: remote.send_command
  
  #######################################################################
  # Volume Control Scripts - Bedroom
  #######################################################################
      
  # Bedroom Volume Plus (Up)
  harmony_bedroom_volume_plus:
    alias: 'Harmony: Bedroom Volume Plus'
    sequence:
    - data:
        command:
        - VolumeUp
        device: Project Audio Systems Amp
      entity_id: remote.harmony_bedroom
      service: remote.send_command
      
  # Bedroom Minus (Down)
  harmony_bedroom_volume_minus:
    alias: 'Harmony: Bedroom Volume Minus'
    sequence:
    - data:
        command:
        - VolumeDown
        device: Project Audio Systems Amp
      entity_id: remote.harmony_bedroom
      service: remote.send_command      
      
  # Turn off all Harmony remotes
  harmony_turn_all_remotes_off:          
    alias: 'Harmony: Turn all remotes off'
    sequence:
    - data:
        activity: PowerOff
      entity_id: remote.harmony_lounge
      service: remote.turn_off
    - data:
        activity: PowerOff
      entity_id: remote.harmony_bedroom
      service: remote.turn_off
    - data:
        activity: PowerOff
      entity_id: remote.harmony_kitchen
      service: remote.turn_off

############################ Harmony Automations ########################################################
# Automations
#########################################################################################################
automation:
  #######################################################################
  # Power On Automations - Lounge
  #######################################################################
  - id: '1577603465751'
    # Freesat TV inputs on Amp & Samsung TV after delay
    alias: 'Harmony: Freesat TV inputs on Amp & Samsung TV after delay'
    description: Change inputs for Freesat TV after delay
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: PowerOff
      platform: state
      to: TV
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_on
    - data:
        command:
        - InputOpt1
        delay_secs: 10
        device: Audiolab CDQ
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command
    - data:
        command:
        - InputHdmi3
        delay_secs: 10
        device: Samsung TV
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  - id: '1577604128899'
    # iPlayer inputs on Amp & Samsung TV after delay
    alias: 'Harmony: iPlayer inputs on Amp & Samsung TV after delay'
    description: Change inputs for iPlayer
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: PowerOff
      platform: state
      to: iPlayer
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_on    
    - data:
        command:
        - InputOpt1
        delay_secs: 10
        device: Audiolab CDQ
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command
    - data:
        command:
        - InputHdmi1
        delay_secs: 10
        device: Samsung TV
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  - id: '1577604536415'
    # BluRay inputs on Amp & Samsung TV after delay
    alias: 'Harmony: BluRay inputs on Amp & Samsung TV after delay'
    description: Change inputs for BluRay after delay
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: PowerOff
      platform: state
      to: BluRay
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_on
    - data:
        command:
        - InputOpt1
        delay_secs: 10
        device: Audiolab CDQ
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command
    - data:
        command:
        - InputHdmi2
        delay_secs: 10
        device: Samsung TV
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  - id: '1577617513820'
    # Lounge Cast input on Amp after delay
    alias: 'Harmony: Lounge Cast input on Amp after delay'
    description: Change input for Audio Cast after delay
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: PowerOff
      platform: state
      to: Lounge Cast
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_on
    - data:
        command:
        - InputAux
        delay_secs: 10
        device: Audiolab CDQ
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  #######################################################################
  # Turn off Amplifier
  #######################################################################
  - id: '1578261907987'
    alias: 'Harmony: Switch off Amplifier'
    description: Switch off Amplifier
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      platform: state
      to: PowerOff
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_off
  #######################################################################
  # Fix input automations
  #######################################################################
  # Change to HDMI2 input when switching from TV or iPlayer to BluRay
  - id: '1577619195425'
    alias: 'Harmony: BluRay input on Samsung TV'
    description: Change Samsung TV input for BluRay
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: TV
      platform: state
      to: BluRay
    - entity_id: sensor.harmony_lounge_activity
      from: iPlayer
      platform: state
      to: BluRay
    condition: []
    action:
    - data:
        command:
        - InputHdmi2
        device: Samsung TV
      entity_id: remote.harmony_lounge
      service: remote.send_command
  
  # Change to HDMI2 input when switching from TV or iPlayer to BluRay with repeat as TV will be off
  - id: '15776191954254'
    alias: 'Harmony: BluRay input on Samsung TV'
    description: Change Samsung TV input for BluRay
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: Lounge Cast
      platform: state
      to: BluRay
    condition: []
    action:
    - data:
        command:
        - InputHdmi2
        delay_secs: 4
        device: Samsung TV
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command      
      
  # Change to HDMI3 input when switching BluRay or iPlayer to TV
  - id: '1577619285401'
    alias: 'Harmony: Freesat TV input on Samsung TV'
    description: Change Samsung TV input for Freesat TV
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: BluRay
      platform: state
      to: TV
    - entity_id: sensor.harmony_lounge_activity
      from: iPlayer
      platform: state
      to: TV
    condition: []
    action:
    - data:
        command:
        - InputHdmi3
        device: Samsung TV
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  # Change to HDMI3 input when switching Audio to TV with delay as TV needs to turn on
  - id: '15776192854014'
    alias: 'Harmony: Freesat TV input on Samsung TV from Audio'
    description: Change Samsung TV input for Freesat TV
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: Lounge Cast
      platform: state
      to: TV
    condition: []
    action:
    - data:
        command:
        - InputHdmi3
        delay_secs: 4
        device: Samsung TV
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command
            
  # Change to HDMI1 input when switching from TV or BluRay to iPlayer
  - id: '1577619361103'
    alias: 'Harmony: iPlayer input on Samsung TV'
    description: Change Samsung TV input for iPlayer
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: TV
      platform: state
      to: iPlayer
    - entity_id: sensor.harmony_lounge_activity
      from: BluRay
      platform: state
      to: iPlayer
    condition: []
    action:
    - data:
        command:
        - InputHdmi1
        device: Samsung TV
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  # Change to HDMI1 input when switching from Audio to iPlayer with delay as TV needs to turn on
  - id: '15776193611034'
    alias: 'Harmony: iPlayer input on Samsung TV'
    description: Change Samsung TV input for iPlayer
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: Lounge Cast
      platform: state
      to: iPlayer
    condition: []
    action:
    - data:
        command:
        - InputHdmi1
        delay_secs: 4
        device: Samsung TV
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command      


