
############################ Harmony Remote Automations, Scripts & Sensors ############################ 
# See https://www.home-assistant.io/integrations/harmony
# All entities to have the prefix: "harmony_" or name: "Harmony:"
# 
# Table of Contents
#   Emulated Hue
#     Emulated Hue for Integration of HA entities into Logitech Harmony Hub
#
#   Sensors
#     Harmony Lounge Activity
#     Harmony Bedroom Activity
#
#   Switches
#     Harmony Lounge 
#       Freesat TV
#       BluRay
#       Google TV
#       Lounge Music
#     Harmony Bedroom 
#       Freeview TV
#       YouView TV
#       Bedroom Google TV
#       Bedroom Music
#
#  Scripts
#    Lounge Volume Plus (Up)
#    Lounge Volume Minus (Down)
#    Lounge Mute
#    Bedroom Volume Plus (Up)
#    Bedroom Minus (Down)
#
#  Automations
#    Freesat TV inputs on Amp & Samsung TV after delay
#    iPlayer inputs on Amp & Samsung TV after delay
#    BluRay inputs on Amp & Samsung TV after delay
#    Music input on Amp after delay
#    Switch off Amplifier
#    Change to HDMI2 input when switching from TV or Google TV to BluRay
#    Change to HDMI2 input when switching from TV or Google TV to BluRay with repeat as TV will be off
#    Change to HDMI1 input when switching BluRay or Google TV to TV
#    Change to HDMI3 input when switching from TV or BluRay to Google TV
#    Change to HDMI3 input when switching from Audio to Google TV with delay as TV needs to turn on
#
#  Conf files:
#    Harmony Lounge: harmony_5710153.conf
#    Harmony Bedroom: harmony_16100813.conf


############################ Emulated Hue  ##############################
# Emulated Hue for Integration of HA entities into Logitech Harmony Hub
# https://www.home-assistant.io/integrations/emulated_hue/
# Check working using
#   http://hassio.bovi.co.uk/description.xml
#   http://hassio.bovi.co.uk/api/pi/lights
emulated_hue:
  host_ip: 192.168.1.10
  listen_port: 80  
  expose_by_default: false
  # exposed_domains:    - light    - switch    - scene
  entities:
    light.led_lights:
      name: "LED Lights"
      hidden: false
    switch.s4_fairy_lights:
      name: "Fairy Lights"
      hidden: false
    switch.s7_tree_lights:
      name: "Tree Lights"
      hidden: false


############################ Harmony Sensors ############################ 
sensor:
  - platform: template
    sensors:
      harmony_lounge_activity:
        friendly_name: 'Harmony Lounge Activity'
        value_template: >-
          {{ state_attr("remote.harmony_lounge", "current_activity") }}
        icon_template: mdi:remote
        
      harmony_bedroom_activity:
        friendly_name: 'Harmony Bedroom Activity'
        value_template: >-
          {{ state_attr("remote.harmony_bedroom", "current_activity") }}
        icon_template: mdi:remote

############################ Harmony Switches ############################ 
switch:
- platform: template
  switches:
    # Lounge TV
    harmony_lounge_tv:
      friendly_name: Freesat TV
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'Freesat TV') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_lounge
          activity: 'Freesat TV'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_lounge
          activity: 'Freesat TV'
      icon_template: >-
          {% if is_state('switch.harmony_lounge_tv', 'on') %}
            mdi:television-classic
          {% else %}
            mdi:television-classic-off
          {% endif %}          

    # Lounge BluRay
    harmony_lounge_bluray:
      friendly_name: BluRay
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'BluRay') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_lounge
          activity: BluRay
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_lounge
          activity: BluRay
      icon_template: mdi:disc-player
      
    # Lounge Google TV
    harmony_lounge_google_tv:
      friendly_name: Google TV
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'Google TV') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_lounge
          activity: 'Google TV'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_lounge
          activity: 'Google TV'
      icon_template: >-
          {% if is_state('switch.harmony_lounge_google_tv', 'on') %}
            mdi:television-play
          {% else %}
            mdi:television-off
          {% endif %}

    # Music
    harmony_lounge_cast:
      friendly_name: Lounge Music
      value_template: >-
        {{ is_state_attr('remote.harmony_lounge', 'current_activity', 'Music') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_lounge
          activity: 'Music'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_lounge
          activity: 'Music'
      icon_template: >-
          {% if is_state('switch.harmony_lounge_cast', 'on') %}
            mdi:cast-audio
          {% else %}
            mdi:speaker-off
          {% endif %}
          
############################################## BEDROOM ##############################################          
    # Bedroom Freeview TV
    harmony_bedroom_tv:
      friendly_name: Freeview TV
      value_template: >-
        {{ is_state_attr('remote.harmony_bedroom', 'current_activity', 'Freeview TV') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_bedroom
          activity: 'Freeview TV'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_bedroom
          activity: Freeview TV
      icon_template: >-
          {% if is_state('switch.harmony_bedroom_tv', 'on') %}
            mdi:television-classic
          {% else %}
            mdi:television-classic-off
          {% endif %}
          
   # Bedroom YouView TV
    harmony_bedroom_youview:
      friendly_name: YouView TV
      value_template: >-
        {{ is_state_attr('remote.harmony_bedroom', 'current_activity', 'YouView TV') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_bedroom
          activity: YouView
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_bedroom
          activity: YouView
      icon_template: >-
          {% if is_state('switch.harmony_bedroom_youview', 'on') %}
            mdi:television-classic
          {% else %}
            mdi:television-classic-off
          {% endif %}
          
   # Bedroom Google TV
    harmony_bedroom_google_tv:
      friendly_name: Bedroom Google TV
      value_template: >-
        {{ is_state_attr('remote.harmony_bedroom', 'current_activity', 'Google TV') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_bedroom
          activity: 'Google TV'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_bedroom
          activity: 'Google TV'
      icon_template: >-
          {% if is_state('switch.harmony_bedroom_google_tv', 'on') %}
            mdi:television-play
          {% else %}
            mdi:television-off
          {% endif %}      
                    
    # Bedroom Audio Cast - Music
    harmony_bedroom_audio_cast:
      friendly_name: Bedroom Music
      value_template: >-
        {{ is_state_attr('remote.harmony_bedroom', 'current_activity', 'Music') }}
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_bedroom
          activity: 'Music'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.harmony_bedroom
          activity: 'Music'
      icon_template: >-
          {% if is_state('switch.harmony_bedroom_audio_cast', 'on') %}
            mdi:cast-audio
          {% else %}
            mdi:speaker-off
          {% endif %}    

 
############################ Harmony Scripts ############################        
# Scripts
#########################################################################
script:
  #######################################################################
  # Volume Control Scripts - Lounge
  #######################################################################
  # Lounge Volume Plus (Up)
  harmony_volume_plus:
    alias: 'Harmony: Volume Plus'
    sequence:
    - data:
        command:
        - VolumeUp
        device: 'Audiolab CDQ'
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  # Lounge Volume Minus (Down)
  harmony_volume_minus:
    alias: 'Harmony: Volume Minus'
    sequence:
    - data:
        command:
        - VolumeDown
        device: 'Audiolab CDQ'
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  # Lounge Mute
  harmony_volume_mute:
    alias: 'Harmony: Volume Mute'
    sequence:
    - data:
        command:
        - Mute
        device: 'Audiolab CDQ'
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  
  #######################################################################
  # Volume Control Scripts - Bedroom
  #######################################################################
      
  # Bedroom Volume Plus (Up)
  harmony_bedroom_volume_plus:
    alias: 'Harmony: Bedroom Volume Plus'
    sequence:
    - data:
        command:
        - VolumeUp
        device: Project Audio Amp
      entity_id: remote.harmony_bedroom
      service: remote.send_command
      
  # Bedroom Minus (Down)
  harmony_bedroom_volume_minus:
    alias: 'Harmony: Bedroom Volume Minus'
    sequence:
    - data:
        command:
        - VolumeDown
        device: Project Audio Amp
      entity_id: remote.harmony_bedroom
      service: remote.send_command      
      
  # Turn off all Harmony remotes
  harmony_turn_all_remotes_off:          
    alias: 'Harmony: Turn all remotes off'
    sequence:
    - data:
        activity: PowerOff
      entity_id: remote.harmony_lounge
      service: remote.turn_off
    - data:
        activity: PowerOff
      entity_id: remote.harmony_bedroom
      service: remote.turn_off   

############################ Harmony Automations ########################################################
# Automations
#########################################################################################################
automation:
  #######################################################################
  # Power On Automations - Lounge
  #######################################################################
  # 
  # Lounge Samsung TV
  #   - HDMI 1 = Freesat TV
  #   - HDMI 2 = BluRay
  #   - HDMI 3 = Google TV
  #  Lounge Audiolab CDQ
  #   - Opt 1 = Samsung TV
  #   - Opt 2 = Music
  #
  #######################################################################  
  - id: '1577603465751'
    # Freesat TV inputs after delay
    alias: 'Harmony: PowerOn: Freesat TV inputs after delay'
    description: Change inputs for Freesat TV after delay
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: PowerOff
      platform: state
      to: 'Freesat TV'
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_on
    - data:
        command:
        - InputOpt1
        delay_secs: 12
        device: 'Audiolab CDQ'
        num_repeats: 2
      entity_id: remote.harmony_lounge
      service: remote.send_command
    - data:
        command:
        - InputHdmi1
        delay_secs: 12
        device: 'Samsung TV'
        num_repeats: 2
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  - id: '1577604128899'
    # Google TV inputs on after delay
    alias: 'Harmony: PowerOn: Google TV inputs after delay'
    description: Change inputs for Google TV
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: PowerOff
      platform: state
      to: 'Google TV'
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_on    
    - data:
        command:
        - InputOpt1
        delay_secs: 12
        device: 'Audiolab CDQ'
        num_repeats: 2
      entity_id: remote.harmony_lounge
      service: remote.send_command
    - data:
        command:
        - InputHdmi3
        delay_secs: 12
        device: 'Samsung TV'
        num_repeats: 2
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  - id: '1577604536415'
    # BluRay inputs after delay
    alias: 'Harmony: PowerOn: BluRay inputs after delay'
    description: Change inputs for BluRay after delay
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: PowerOff
      platform: state
      to: BluRay
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_on
    - data:
        command:
        - InputOpt1
        delay_secs: 12
        device: 'Audiolab CDQ'
        num_repeats: 2
      entity_id: remote.harmony_lounge
      service: remote.send_command
    - data:
        command:
        - InputHdmi2
        delay_secs: 12
        device: 'Samsung TV'
        num_repeats: 2
      entity_id: remote.harmony_lounge
      service: remote.send_command
      
  - id: '1577617513820'
    # Music input after delay
    alias: 'Harmony: PowerOn: Audio Cast input after delay'
    description: Change input for Audio Cast after delay
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: PowerOff
      platform: state
      to: 'Music'
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_on
    - data:
        command:
        - InputOpt2
        delay_secs: 12
        device: 'Audiolab CDQ'
        num_repeats: 2
      entity_id: remote.harmony_lounge
      service: remote.send_command
      

  #######################################################################
  # TV Power On Automations - Lounge
  #   Send input command after delay as TV takes a while to come on
  #   Only for Audio Cast to TV mode
  #######################################################################      
  # Change to HDMI1 input when switching Music to Freesat TV with delay as TV needs to turn on
  - id: '15776192854014'
    alias: 'Harmony: PowerOn TV: Freesat TV input with delay'
    description: Change Samsung TV input for Freesat TV
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: 'Music'
      platform: state
      to: 'Freesat TV'
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_on    
    - data:
        command:
        - InputHdmi1
        delay_secs: 4
        device: Samsung TV
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command
            
  # Change to HDMI3 input when switching from Music to Google TV with delay as TV needs to turn on
  - id: '15776193611034'
    alias: 'Harmony: PowerOn TV: Google TV input with delay'
    description: Change Samsung TV input for Google TV with delay
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      from: 'Music'
      platform: state
      to: 'Google TV'
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_on
    - data:
        command:
        - InputHdmi3
        delay_secs: 4
        device: Samsung TV
        num_repeats: 3
      entity_id: remote.harmony_lounge
      service: remote.send_command      
      
  #######################################################################
  # Turn off Amplifier
  #######################################################################
  - id: '1578261907987'
    alias: 'Harmony: Switch off Amplifier'
    description: Switch off Amplifier
    trigger:
    - entity_id: sensor.harmony_lounge_activity
      platform: state
      to: PowerOff
    condition: []
    action:
    - entity_id: switch.s1_amplifier
      service: switch.turn_off

 
      

