
 

# https://www.home-assistant.io/integrations/miflora/

sensor:
  - platform: miflora
    name: Mi Flora 1
    mac: !secret miflora1
  

# https://www.home-assistant.io/integrations/plant
plant:
  johns_trough:
    sensors:
      moisture: sensor.mi_flora_1_moisture
      battery: sensor.mi_flora_1_battery
      temperature: sensor.mi_flora_1_temperature
      conductivity: sensor.mi_flora_1_conductivity
      brightness: sensor.mi_flora_1_light_intensity
    min_moisture: 20
    max_moisture: 60
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 6
    max_temperature: 32
    min_brightness: 2200
    max_brightness: 30000
