
############################ Network Automations, Scripts & Sensors ###################################### 
# Various network/computer sensors and scripts supported through various components
#
# All entities to have a prefix suitable for the computer they are referencing.  e.g. nas710
######################################################################################################

# Table of Contents
#   Config Elements
#     Wake on LAN
#
#   Shell Commands
#     NAS710 Shutdown
#     NAS710 Start Plex
#     NAS710 Copy Public/Private Keys to correct location in the Docker container
#
#   Sensors
#     System Monitor 
#     HA Uptime 
#     Pi CPU Temperature
#
#   Binary Sensors Ping
#      Internet Connection
#      pfSense Router
#      LTE Modem
#      NAS710
#      Desktop PC
#      EY Laptop
#
#   Binary Sensors
#      HA Upgraded
#      Desktop PC Status
#      EY Laptop Status
#      Unifi WAP Upstairs
#      Unifi WAP Kitchen
#      Network
#
#   Scripts
#      NAS710 Wake on LAN
#      NAS710 Shutdown
#      NAS710 Start Plex
#      Desktop PC: Wake on LAN
#      Desktop PC: Shutdown
#      Reset HA Upgraded Flag
#
#   Automations
#      NAS710: Copy Keys after HA Upgraded
#      Notify when Internet connection dies entirely
#      Notify when Virgin broadband goes off-line
#      Notify when Tesco Mobile LTE backup goes off-line
#
#   Netgear LTD Modem Config
#
#   Switches
#      Netgear NAS710
#
############################ Network Config Elements ############################ 
wake_on_lan:

# This is now an integration.  So need to disable there too!
#speedtestdotnet:  
#  server_id: 11445  # Structured Communications
#  scan_interval:
#    minutes: 60

############################ Network Shell Commands ############################ 

# https://www.home-assistant.io/integrations/shell_command/
# https://www.ssh.com/cryptography/public-key
shell_command:
  # NAS710 Shutdown
  nas710_shutdown: ssh root@192.168.1.11 rnutil rn_shutdown
  # NAS710 Start Plex
  nas710_start_plex: ssh root@192.168.1.11 systemctl start fvapp-plexmediaserver
  # NAS710 Copy Public/Private Keys to correct location in the Docker container
  nas710_copy_keys: sh ./nas710/install_ssh_keypair.sh
  
  
############################ Network Sensors ############################ 
sensor:
  # System Monitor 
  #   Provides time since last reboot plus disk, memory and processor usage 
  #   See https://www.home-assistant.io/integrations/systemmonitor/
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: last_boot       # Last Raspberry Pi reboot
      - type: processor_use
  
  # HA Uptime 
  #   Provides how long since last HA restart
  - platform: uptime
    name: HA Uptime
    unit_of_measurement: "hours"
  
  # Pi CPU Temperature
  - platform: command_line
    name: Pi CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  
############################ Network Binary Sensors ############################ 
binary_sensor:
# https://community.home-assistant.io/t/function-to-check-internet-status/38504/10
- platform: ping
  name: internet_connection
  host: 216.239.38.120     # Google
  count: 2           # Two Pings
  scan_interval: 30  # Every 30 seconds

- platform: ping
  name: pfSense Router
  host: 192.168.1.1    
  count: 2           # Two Pings
  scan_interval: 5   # Every 5 seconds

- platform: ping
  name: LTE Modem
  host: 192.168.5.1  # on different subnet
  count: 2           # Two Pings
  scan_interval: 10  # Every 10 seconds

- platform: ping
  name: nas710
  host: 192.168.1.11
  count: 2          # Two Pings
  scan_interval: 5  # Every 5 seconds          

- platform: ping
  name: drjohnt_desktop_pc
  host: 192.168.1.12
  count: 2          # Two Pings
  scan_interval: 5  # Every 5 seconds   

- platform: ping
  name: laptop_ey
  host: 192.168.1.34
  count: 2           # Two Pings
  scan_interval: 10  # Every 10 seconds   

- platform: template
  sensors:
        
    # HA Upgraded 
    ha_upgraded:
      friendly_name: 'HA Upgraded'
      value_template: >-
        {{ is_state('input_text.ha_upgraded', 'on') }}
      icon_template: mdi:home-assistant
    
    # Desktop PC Status
    desktop_pc_status:
      friendly_name: 'Desktop PC Status'
      value_template: >-
        {{ is_state('binary_sensor.drjohnt_desktop_pc', 'on') }}
      icon_template: >-
        {% if is_state('binary_sensor.drjohnt_desktop_pc', 'on') %}
          mdi:server-network
        {% else %}
          mdi:server-network-off
        {% endif %}    
        
    # EY Laptop Status
    laptop_ey_status:
      friendly_name: 'EY Laptop Status'
      value_template: >-
        {{ is_state('binary_sensor.laptop_ey', 'on') }}
      icon_template: >-
        {% if is_state('binary_sensor.laptop_ey', 'on') %}
          mdi:laptop
        {% else %}
          mdi:laptop-off
        {% endif %}              
           
    unifi_wap_upstairs:
      friendly_name: 'Unifi WAP Upstairs'
      value_template: >-
        {{ is_state('device_tracker.unifi_wap_upstairs', 'home') }}
      icon_template: >-
        {% if is_state('binary_sensor.unifi_wap_upstairs', 'on') %}
          mdi:access-point-network
        {% else %}
          mdi:access-point-network-off
        {% endif %}    

    unifi_wap_kitchen:
      friendly_name: 'Unifi WAP Kitchen'
      value_template: >-
        {{ is_state('device_tracker.unifi_wap_kitchen', 'home') }}
      icon_template: >-
        {% if is_state('binary_sensor.unifi_wap_kitchen', 'on') %}
          mdi:access-point-network
        {% else %}
          mdi:access-point-network-off
        {% endif %}               
    
    network_status:
      friendly_name: Network
      value_template: >-
        {{ 
          is_state('binary_sensor.internet_connection', 'on') 
          or is_state('sensor.netgear_lte_upstream', 'WAN')
          or is_state('binary_sensor.pfsense_router', 'on') 
          or is_state('binary_sensor.unifi_wap_upstairs', 'on') 
          or is_state('binary_sensor.unifi_wap_kitchen', 'on') 
        }}
      icon_template: >-
        {% if is_state('binary_sensor.network_status', 'on') %}
          mdi:server-network
        {% else %}
          mdi:server-network-off
        {% endif %}  

############################ Network Scripts ############################ 
script:
  ############################ Wake on LAN ############################ 
  # NAS710: Wake on LAN
  nas710_wake_on_lan:
    alias: NAS710 Wake on LAN
    sequence:
    - data:
        mac: B0:7F:B9:44:FF:DA
      service: wake_on_lan.send_magic_packet

  # Desktop PC: Wake on LAN
  desktop_pc_wake_on_lan:
    alias: 'Desktop PC: Wake on LAN'
    sequence:
    - entity_id: switch.s5_study_computer
      service: switch.turn_on
    - delay: 0:00:03
    - data:
        mac: BC:EE:7B:5B:EE:DA
      service: wake_on_lan.send_magic_packet

  # Laptop EY: Wake on LAN
  laptop_ey_wake_on_lan:
    alias: 'Laptop EY: Wake on LAN'
    sequence:
    - entity_id: switch.s5_study_computer
      service: switch.turn_on
    - delay: 0:00:03
    - data:
        mac: b4:b6:86:8b:4b:e6
      service: wake_on_lan.send_magic_packet
       
  ############################ Shutdown ############################ 
  # NAS710: Shutdown
  nas710_shutdown:
    alias: NAS710 Shutdown
    sequence:
    - service: shell_command.nas710_shutdown
    
  # NAS710: Start Plex
  nas710_start_plex:
    alias: NAS710 Start Plex
    sequence:
    - service: shell_command.nas710_start_plex
      
  # Desktop PC: Shutdown
  desktop_pc_shutdown:
    alias: 'Desktop PC: Shutdown'
    sequence:
    - data:
        addon: core_rpc_shutdown
        input: DesktopPC
      service: hassio.addon_stdin
    - delay: 0:01:00
    - entity_id: switch.s5_study_computer
      service: switch.turn_off

  ############################ Copy Keys ############################ 
  # NAS710: Copy Public/Private Keys to correct location in the Docker container
  nas710_copy_keys:
    alias: NAS710 Copy Public/Private Keys 
    sequence:
    - service: shell_command.nas710_copy_keys
    - data:
        value: 'startup'
      entity_id: input_text.ha_upgraded
      service: input_text.set_value

automation:
# NAS710: Copy Keys after HA Upgraded
- id: nas710_copy_keys_after_ha_upgrade
  alias: 'NAS710: Copy Keys after HA Upgraded'
  description: ''
  trigger:
  - entity_id: binary_sensor.ha_upgraded
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: script.nas710_copy_keys
    service: script.toggle

# Notify when Internet connection dies 
- id: notify_when_internet_off_line
  alias: Internet Off-Line
  description: ''
  trigger:
  - entity_id: binary_sensor.internet_connection
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Internet off-line entirely
      title: HA Alert
    service: notify.sms_john

# Notify when Virgin broadband goes off-line
- id: notify_when_broadband_off_line
  alias: 'Broadband Off-Line'
  description: 'Notify when Virgin broadband goes off-line'
  trigger:
  - entity_id: binary_sensor.netgear_lte_wire_connected
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Virgin broadband off-line
      title: HA Alert
    service: notify.sms_john

# Notify when Tesco Mobile LTE backup goes off-line
- id: notify_when_lte_backup_off_line
  alias: 'LET Backup Off-Line'
  description: 'Notify when Tesco Mobile LTE backup goes off-line'
  trigger:
  - entity_id: binary_sensor.netgear_lte_mobile_connected
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Tesco Mobile LTE backup off-line
      title: HA Alert
    service: notify.sms_john

############################ Netgear LTD Modem Config ############################ 
# https://www.home-assistant.io/integrations/netgear_lte/
# @amelchio maintains the integration
netgear_lte:
  - host: !secret netgear_lte_ip
    password: !secret netgear_lte_pwd
    notify:
      - name: sms_john
        recipient: !secret mobile_number_john
      - name: sms_irina
        recipient: !secret mobile_number_irina
    sensor:
      monitored_conditions:
        - upstream       # Shows WAN or LTE??
        - usage          # Data Usage this month
        - radio_quality  # Quality of reception e.g. 43%
        - current_band   # Shows LTE B40
        - sms            # Total number of UNREAD SMS messages in the inbox        
        - sms_total      # Total number of SMS messages in the inbox        
    binary_sensor:
      monitored_conditions:
        - wire_connected    # Wired connection available
        - mobile_connected  # Mobile connection available

switch:        
# See https://www.home-assistant.io/integrations/switch.template/
  - platform: template
    switches:
      netgear_nas710:
        friendly_name: 'NAS710'
        value_template: >-
          {{ is_state('binary_sensor.nas710', 'on') }}
        icon_template: >-
          {% if is_state('binary_sensor.nas710', 'on') %}
            mdi:server
          {% else %}
            mdi:server-off
          {% endif %}   
        turn_on:
          service: script.nas710_wake_on_lan
        turn_off:
          service: script.nas710_shutdown
    