############################ Plex Automations, Scripts & Sensors #############################
# Plex config
#   See https://www.home-assistant.io/integrations/plex
#   Note that this is auto-detected and needs no config
#
# Plex Assistant config 
#   See https://community.home-assistant.io/t/plex-assistant/173937
#
# All entities to have the prefix: "plex_" or name: Plex: 
##############################################################################################


#plex_assistant:
#  url: !secret plex_url
#  token: !secret plex_token
#  default_cast: 'Lounge TV Chromecast'
#  language: en
#  tts_errors: true

#sensor:
#  # creates a sensor called sensor.plex_assistant_devices
#  - platform: plex_assistant


#conversation:
#  intents:
#    PlexAssistant:
#     # These trigger commands can be changed to suit your needs.
#     - "Tell Plex to {command}"
#     - "{command} with Plex"

#intent_script:
#  Plex:
#    speech:
#      text: Command sent to Plex.
#    action:
#      - service_template: plex_assistant.command
#        data_template:
#          command: "{{command}}"
#  PlexAssistant:
#    speech:
#      text: Command sent to Plex.
#    action:
#      service: plex_assistant.command
#      data_template:
#        command: "{{command}}"          

