
############################ Power Automations, Scripts & Sensors ###################################### 
# Mostly scripts to turn stuff off
#
# Table of Contents
#   Scripts
#     Turn OFF all Lights
#     Turn OFF everything
######################################################################################################

script:
  turn_off_all_lights:
    alias: Turn OFF all Lights
    sequence:
    - entity_id: switch.s3_hall_light
      service: switch.turn_off
    - entity_id: switch.s4_fairy_lights
      service: switch.turn_off
    - entity_id: switch.s7_upstairs_light
      service: switch.turn_off
    - entity_id: light.led_lights
      service: light.turn_off
    - entity_id: light.led_hall
      service: light.turn_off
    
  turn_off_everything:
    alias: Turn OFF everything
    sequence:
    # Turn off all TVs and Audio using Harmony remotes
    - service: script.harmony_turn_all_remotes_off   
    # Close all windows
    - service: script.velux_close_all_windows
    # Turn of the heating
    - service: script.wiser_heating_off
    # Turn off SmartThings switches
    - entity_id: switch.s1_amplifier
      service: switch.turn_off
    - entity_id: switch.s2_bosch_battery_charger
      service: switch.turn_off
    - entity_id: switch.s3_hall_light
      service: switch.turn_off
    - entity_id: switch.s4_fairy_lights
      service: switch.turn_off
    - entity_id: switch.s5_study_computer
      service: switch.turn_off
    - entity_id: switch.s6_desk_charger
      service: switch.turn_off
    - entity_id: switch.s7_upstairs_light
      service: switch.turn_off
    # Turn of Fans
    - entity_id: switch.bathroom_fan
      service: switch.turn_off
    - entity_id: switch.ensuite_fan
      service: switch.turn_off
    # Turn off Kitchen Amp
    - entity_id: switch.kitchen_amp
      service: switch.turn_off
    # Turn off LED lights 
    - entity_id: light.led_lights
      service: light.turn_off
    - entity_id: light.led_hall
      service: light.turn_off
    # NAS710: Shutdown
    - service: script.nas710_shutdown

sensor:
- platform: template
  sensors:
    total_consumption:
      friendly_name: Total Consumption
      device_class: power
      unit_of_measurement: kWh
      icon_template: mdi:power-settings
      value_template: >-
        {{ 
          (states('sensor.s1_consumption') | float) + 
          (states('sensor.s2_consumption') | float) +
          (states('sensor.s3_consumption') | float) +
          (states('sensor.s4_consumption') | float) +
          (states('sensor.s5_consumption') | float) +
          (states('sensor.s6_consumption') | float) +
          (states('sensor.s7_consumption') | float) 
        }}
