
############################ Risco Automations, Scripts & Sensors ####################################
# All entities to have the prefix: "risco_" or name: Risco: 
# 
# Risco Alarm integration done using https://www.home-assistant.io/integrations/risco/
######################################################################################################

# Table of Contents
#
#   Binary Sensors
#     Risco Alarm On-Line
#     Risco Alarm Status
#
#   Script
#     Risco Alarm Set
#     Risco Alarm Unset
#
#   Automation
#     Risco Alarm Set: Check Windows Closed


############################ Risco Binary Sensors ############################ 
binary_sensor:

- platform: ping
  name: Risco Alarm Panel
  host: 192.168.1.17
  count: 2         
  scan_interval: 10

- platform: template
  sensors:
    # Risco Alarm On-Line - simply returns true / on when the Risco Alarm panel is connected to the network - was once off-line due to router reconfig 
    risco_alarm_online:
      friendly_name: 'Risco Alarm On-Line'
      value_template: >-
        {{ is_state('binary_sensor.risco_alarm_panel', 'on') }}      
      icon_template: >-
        {% if is_state('binary_sensor.risco_alarm_online', 'on') %}
          mdi:shield
        {% else %}
          mdi:shield-alert
        {% endif %}  
        
    # Risco Alarm Status - shows a Bell alert icon if alarm set
    risco_alarm_status:
      friendly_name: 'Risco Alarm Status'
      value_template: >-
        {{ not is_state('alarm_control_panel.risco_alarm', 'disarmed') }}  
      icon_template: >-
          {% if is_state('binary_sensor.risco_alarm_status', 'on') %}
            mdi:bell-check
          {% else %}
            mdi:bell-off-outline
          {% endif %}

############################ Risco Scripts ############################ 
script:
  # Risco Alarm Set
  risco_alarm_set:
    alias: 'Risco: Alarm Set'
    sequence:
    - data: 
        code: !secret risco_arm_code
      entity_id: alarm_control_panel.risco_alarm
      service: alarm_control_panel.alarm_arm_away

  # Risco Alarm Unset
  risco_alarm_unset:
    alias: 'Risco: Alarm Unset'
    sequence:
    - data: 
        code: !secret risco_arm_code
      entity_id: alarm_control_panel.risco_alarm
      service: alarm_control_panel.alarm_disarm
      

############################ Risco Automations ############################ 

automation:
#     Risco Alarm Set: Check Windows Closed
- id: risco_check_windows_closed_when_alarm_set
  alias: 'Risco Alarm Set: Check Windows Closed'
  description: ''
  trigger:
  - entity_id: binary_sensor.risco_alarm_status
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.bedroom_window
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.guest_room_window
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.lounge_window
        state: 'on'
  action:
  - data:
      message: A window is open! Go back and check!
    service: notify.mobile_app_pixel_3a
  - data:
      message: A window is open! Go back and check!
    service: notify.mobile_app_lenovo_p2a42
