############################ Wiser Heating Automations, Scripts & Sensors ############################ 
# Wiser Heating config 
# See https://github.com/asantaga/wiserHomeAssistantPlatform
# All entities to have the prefix: "wiser_" or name: Wiser: 
######################################################################################################

# Table of Contents
#
#   Config Elements
#
#   Sensors
#     Temperature
#       Lounge Temperature
#       Upstairs Temperature
#       Bedroom Temperature
#       Guest Temperature
#     Humidity
#       Lounge Humidity
#       Upstairs Humidity
#
#   Binary Sensors
#     Heating Is On
#     Hot Water Is On 
#
#   Scripts
#     Heating Off
#     Hot Water On
#     Hot Water Auto
#     Hot Water Off
#
#   Automations
#     Close Windows when the heating has been switched on 
#     Switch OFF Heating at 22:30 on weekdays      
#     Switch OFF Heating at 23:30 on weekends 
#     Switch ON Heating in Guest Room when Guest Button pressed
#     Switch OFF Heating in Guest Room when Guest Button pressed
#     Bathroom Radiator may be on warning - has standard radiator valve
#
#   Switches
#     Hot Water
#     Heating Lounge
#     Heating Bedroom
#     Heating Kitchen
#     Heating Guest Room
#     Heating Upstairs


############################ Wiser Config Elements ############################ 
# Now done on integrations screen
#wiser:
#  host: !secret wiser_host
#  password: !secret wiser_secret
#  scan_interval: 300
#  minimum: 0
#  boost_temp: 3
#  boost_time: 60

############################ Wiser Heating Sensors ############################ 
sensor:
  - platform: template
    sensors:
      # Lounge Temperature
      lounge_temperature:
        device_class: temperature
        friendly_name: Lounge Temperature
        value_template: >-
          {{ state_attr("climate.wiser_lounge","current_temperature") }}
        
      # Upstairs Temperature
      upstairs_temperature:
        device_class: temperature
        friendly_name: Upstairs Temperature
        value_template: >-
          {{ state_attr("climate.wiser_upstairs","current_temperature") }}
        
      # Bedroom Temperature
      bedroom_temperature:
        device_class: temperature
        friendly_name: Bedroom Temperature
        value_template: >-
          {{ state_attr("climate.wiser_bedroom","current_temperature") }}
        
      # Guest Temperature
      guest_room_temperature:
        device_class: temperature
        friendly_name: Guest Room Temperature
        value_template: >-
          {{ state_attr("climate.wiser_guest_room","current_temperature") }}
        
      # Lounge Humidity
      lounge_humidity:
        device_class: humidity
        friendly_name: Lounge Humidity
        value_template: >-
          {{ state_attr("sensor.wiser_roomstat_lounge","humidity") }}
        
      # Upstairs Humidity
      upstairs_humidity:
        device_class: humidity
        friendly_name: Upstairs Humidity
        value_template: >-
          {{ state_attr("sensor.wiser_roomstat_upstairs","humidity") }}
        

############################ Wiser Heating Binary Sensors ############################ 
binary_sensor:
  - platform: template
    sensors:
      # Heating Is On 
      heating_is_on:
        friendly_name: 'Heating'
        # Returns 'on' if the heating is on
        value_template: >-
          {{ is_state('sensor.wiser_heating', 'On')
             or is_state('climate.wiser_lounge', 'heat')
             or is_state('climate.wiser_upstairs', 'heat') 
             or is_state('climate.wiser_bedroom', 'heat') 
             or is_state('climate.wiser_guest_room', 'heat') 
             or is_state('climate.wiser_kitchen', 'heat') 
             }}   
        icon_template: >-
            {% if is_state('binary_sensor.heating_is_on', 'on') %}
              mdi:radiator
            {% else %}
              mdi:radiator-disabled
            {% endif %}      

############################ Wiser Heating Scripts ############################ 
script:
  # Heating Off
  wiser_heating_off:
    alias: 'Wiser: Heating Off'
    sequence:
    - entity_id: climate.wiser_bedroom
      service: climate.turn_off
    - entity_id: climate.wiser_guest_room
      service: climate.turn_off
    - entity_id: climate.wiser_lounge
      service: climate.turn_off
    - entity_id: climate.wiser_upstairs
      service: climate.turn_off
    - entity_id: climate.wiser_kitchen
      service: climate.turn_off
        
  # Hot Water On
  wiser_hot_water_on:
    alias: 'Wiser: Hot Water On'
    sequence:
    - data:
        hotwater_mode: 'on'
      service: wiser.set_hotwater_mode

  # Hot Water Auto
  wiser_hot_water_auto:
    alias: 'Wiser: Hot Water Auto'
    sequence:
    - data:
        hotwater_mode: 'auto'
      service: wiser.set_hotwater_mode
      
  # Hot Water Off
  wiser_hot_water_off:
    alias: 'Wiser: Hot Water Off'
    sequence:
    - data:
        hotwater_mode: 'off'
      service: wiser.set_hotwater_mode
        
############################ Wiser Heating Automations ############################ 
automation:
  # Close Windows when the heating has been switched on 
  - id: wiser_close_windows_when_heat_on
    alias: 'Wiser: Close windows when heating switched on'
    description: 'Close windows when heating switched on'
    trigger:
    - entity_id: binary_sensor.heating_is_on
      from: 'off'
      platform: state
      to: 'on'
    condition:
    - condition: state
      entity_id: binary_sensor.velux_window_open
      state: 'on'
    action:
    - entity_id: script.velux_close_all_windows
      service: script.toggle
    - data:
        entity_id: media_player.lounge_assistant
        message: Home Assistant is closing all windows as the heating is now on!
      service: tts.google_say
    mode: single
       
  # Warn that a window is open when the heating has been switched on 
  - id: wiser_warn_window_open_when_heating_is_on
    alias: 'Wiser: Warn that window open when heating is on'
    description: Warn that window open when heating is on
    trigger:
    - platform: time_pattern
      minutes: /20
    condition:
    - condition: state
      entity_id: binary_sensor.heating_is_on
      state: 'on'
    - condition: state
      entity_id: binary_sensor.velux_window_open
      state: 'on'
    action:
    - service: tts.google_say
      data:
        entity_id: media_player.lounge_assistant
        message: 'Warning: A window is open when the heating is on!'
    mode: single

           
  # Switch OFF Heating at 22:30 on weekdays
  - id: wiser_switch_off_heating_on_weekday
    alias: 'Wiser: Switch OFF Heating at 22:30 on weekday'
    description: 'Switch OFF Heating at 22:30 on weekday'
    trigger:
    - at: '22:30'
      platform: time
    condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    action:
    - entity_id: script.wiser_heating_off
      service: script.toggle
      
  # Switch OFF Heating at 23:30 on weekends      
  - id: wiser_switch_off_heating_on_weekend
    alias: 'Wiser: Switch OFF Heating at 23:30 at weekend'
    description: 'Switch OFF Heating at 23:30 at weekend'
    trigger:
    - at: '23:30'
      platform: time
    condition:
    - condition: time
      weekday:
      - sat
      - sun
    action:
    - entity_id: script.wiser_heating_off
      service: script.toggle
      
  # Switch ON Heating in Guest Room when Guest Button pressed
  - id: wiser_guest_button_switch_heat_on
    alias: 'Wiser: Guest Button Switch ON Guest Room Heating'
    description: 'Guest Button Switch ON Guest Room Heating'
    trigger:
    - event_data:
        event: 1000
        id: guest_button
      event_type: deconz_event
      platform: event
    condition:
    - condition: state
      entity_id: climate.wiser_guest_room
      state: 'off'
    action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.kitchen_assistant
        volume_level: 0.6    
    - data:
        message: 'Turning on the heating in the Guest Room'
      entity_id: media_player.kitchen_assistant    
      service: tts.google_say         
    - data:
        temperature: 22
      entity_id: climate.wiser_guest_room
      service: climate.set_temperature
      
  # Switch OFF Heating in Guest Room when Guest Button pressed
  - id: wiser_guest_button_switch_heat_off
    alias: 'Wiser: Guest Button Switch OFF Guest Room Heating'
    description: 'Guest Button Switch OFF Guest Room Heating'
    trigger:
    - event_data:
        event: 1000
        id: guest_button
      event_type: deconz_event
      platform: event
    condition:
    - condition: state
      entity_id: climate.wiser_guest_room
      state: heat
    action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.kitchen_assistant
        volume_level: 0.6    
    - data:
        message: 'Turning off the heating in the Guest Room'
      entity_id: media_player.kitchen_assistant    
      service: tts.google_say             
    - data: {}
      entity_id: climate.wiser_guest_room
      service: climate.turn_off

  # Bathroom Radiator may be on warning - has standard radiator valve
  - id: wiser_bathroom_radiator_may_be_on
    alias: 'Wiser: Bathroom radiator may be on warning'
    description: 'Bathroom radiator may be on warning'
    trigger:
    - above: '24'
      entity_id: sensor.temperature_bathroom
      platform: numeric_state
    condition:
    - condition: state
      entity_id: binary_sensor.heating_is_on
      state: 'on'
    action:
    - data:
        message: Bathroom radiator may be on
      service: notify.mobile_app_pixel_3a
    
############################ Wiser Heating Switches ############################ 
switch:
  - platform: template
    switches:
      # Hot Water
      wiser_hot_water:
        friendly_name: Hot Water
        value_template: >-
          {{ is_state('sensor.wiser_hot_water', 'On') }}   
        icon_template: >-
            {% if is_state('sensor.wiser_hot_water', 'On') %}
              mdi:water
            {% elif is_state('sensor.wiser_hot_water', 'Auto') %}
              mdi:water-outline
            {% else %}
              mdi:water-off
            {% endif %}
        turn_on:
          service: script.wiser_hot_water_on
        turn_off:
          service: script.wiser_hot_water_auto

      # Heating Lounge
      wiser_lounge:
        friendly_name: Lounge
        value_template: >-
          {{ not is_state('climate.wiser_lounge', 'off') }}
        # icon_template: mdi:sofa
        icon_template: >-
          {% if is_state('switch.wiser_lounge', 'on') %}
            mdi:radiator
          {% else %}
            mdi:radiator-disabled
          {% endif %}          
        turn_on:
          - data:
              temperature: 22
            entity_id: climate.wiser_lounge
            service: climate.set_temperature
        turn_off:    
          - entity_id: climate.wiser_lounge
            service: climate.turn_off

      # Heating Bedroom
      wiser_bedroom:
        friendly_name: Bedroom
        value_template: >-
          {{ not is_state('climate.wiser_bedroom', 'off') }}
        # icon_template: mdi:bed-empty
        icon_template: >-
          {% if is_state('switch.wiser_bedroom', 'on') %}
            mdi:radiator
          {% else %}
            mdi:radiator-disabled
          {% endif %}           
        turn_on:
          - data:
              temperature: 20
            entity_id: climate.wiser_bedroom
            service: climate.set_temperature
        turn_off:    
          - entity_id: climate.wiser_bedroom
            service: climate.turn_off
            
      # Heating Kitchen
      wiser_kitchen:
        friendly_name: Kitchen
        value_template: >-
          {{ not is_state('climate.wiser_kitchen', 'off') }}
        # icon_template: mdi:food-fork-drink
        icon_template: >-
          {% if is_state('switch.wiser_kitchen', 'on') %}
            mdi:radiator
          {% else %}
            mdi:radiator-disabled
          {% endif %}           
        turn_on:
          - data:
              temperature: 22
            entity_id: climate.wiser_kitchen
            service: climate.set_temperature
        turn_off:    
          - entity_id: climate.wiser_kitchen
            service: climate.turn_off            
      
      # Heating Guest Room
      wiser_guest_room:
        friendly_name: Guest
        value_template: >-
          {{ not is_state('climate.wiser_guest_room', 'off') }}
        # icon_template: mdi:bed-outline
        icon_template: >-
          {% if is_state('switch.wiser_guest_room', 'on') %}
            mdi:radiator
          {% else %}
            mdi:radiator-disabled
          {% endif %}           
        turn_on:
          - data:
              temperature: 22
            entity_id: climate.wiser_guest_room
            service: climate.set_temperature
        turn_off:    
          - entity_id: climate.wiser_guest_room
            service: climate.turn_off     
                        
      # Heating Upstairs
      wiser_upstairs:
        friendly_name: Upstairs
        value_template: >-
          {{ not is_state('climate.wiser_upstairs', 'off') }}
        # icon_template: mdi:home-roof
        icon_template: >-
          {% if is_state('switch.wiser_upstairs', 'on') %}
            mdi:radiator
          {% else %}
            mdi:radiator-disabled
          {% endif %}        
        turn_on:
          - data:
              temperature: 22
            entity_id: climate.wiser_upstairs
            service: climate.set_temperature
        turn_off:    
          - entity_id: climate.wiser_upstairs
            service: climate.turn_off
