
############################ Working from Home Automations, Scripts & Sensors ###################################### 
# Working from Home Automations, Scripts & Sensors
#
# All entities to have the prefix: "wfh_" or name: WFH: 
####################################################################################################################
#
# Table of Contents
#   Scripts
#     WFH: Start
#     WFH: End
#
#   Switches
#     WFH
#
#   Automations
#     Switch on Upstairs Light at Sunset



script:
  # Working From Home Scripts
  working_from_home_start:
    alias: 'WFH: Start'
    sequence:
    - entity_id: switch.s5_study_computer
      service: switch.turn_on
    - data:
        position: 20
      entity_id: cover.velux_south_study_blind
      service: cover.set_cover_position
      
  working_from_home_end:
    alias: 'WFH: End'
    sequence:
    - entity_id: switch.s5_study_computer
      service: switch.turn_off
    - entity_id: switch.s7_upstairs_light
      service: switch.turn_off
    - entity_id: switch.s6_desk_charger
      service: switch.turn_off
      
#switch:
#- platform: template
#  switches:
#    working_from_home:
#      friendly_name: WFH
#      value_template: >-
#        {{ 
#            is_state('switch.s5_study_computer', 'on')
#        }}
#      icon_template: >-
#          {% if is_state('switch.s5_study_computer', 'on') %}
#            mdi:briefcase
#          {% else %}
#            mdi:briefcase-outline
#          {% endif %}
#      turn_on:
#        service: script.working_from_home_start
#      turn_off:    
#        service: script.working_from_home_end

#automation:
## Switch on Upstairs Light at Sunset
#- id: wfh_switch_on_upstairs_light_at_sunset
#  alias: 'WFH: Switch on Upstairs Light at Sunset'
#  description: ''
#  trigger:
#  - event: sunset
#    offset: 00:15
#    platform: sun
#  condition:
#  - condition: state
#    entity_id: switch.working_from_home
#    state: 'on'
#  action:
#  - entity_id: switch.s7_upstairs_light
#    service: switch.turn_on


