- id: set_ui_theme
  alias: 'Setup: Set theme on startup'
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      name: Soft_UI
    service: frontend.set_theme
  - data:
      value: startup
    entity_id: input_text.ha_upgraded
    service: input_text.set_value
  initial_state: 'on'


