
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  ### The following installs all package files
  packages: !include_dir_named packages
  ### The following installs all customizions 
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
      trusted_users:
        192.168.1.24: 4cd6c52e90d84b0a96bda6f9c4b648c4  # User ID 

updater:
  include_used_components: true
  
frontend:
  themes: !include_dir_merge_named themes

python_script:
          
switch: !include switches.yaml
#light: !include light_switch.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
device_tracker: !include device_tracker.yaml

# https://www.home-assistant.io/integrations/logger
# log_level= critical, fatal, error, warning, warn, info, debug, notset
logger:
  default: warning
  logs:
    homeassistant.components.cast: error
    pychromecast.socket_client: error
    miflora: fatal
    #homeassistant.components.device_tracker: debug
    #homeassistant.components.switch.template: debug
    #homeassistant.components.switch.command_line: debug
    #custom_components.wiser: debug
    #homeassistant.components.device_tracker
    #custom_components.plex_assistant: debug
    #homeassistant.components.plex: debug
    #plexapi: debug
    
    #btlewrap: debug
    #bluepy: debug
    
# https://www.home-assistant.io/integrations/recorder/
recorder:
  purge_keep_days: 5
  exclude:
    domains:
    - media_player
    entities:
    - sun.sun 
    - timer.hall_light
    - sensor.wiser_operation_mode
    - switch.wiser_comfort_mode
    - switch.wiser_eco_mode
    - switch.wiser_valve_protection
    - switch.wiser_away_mode_affects_hot_water
    - switch.wiser_away_mode

# Text to speech via Google Translate
tts:
  - platform: google_translate
    cache: true
    #cache_dir: /tmp/tts
    time_memory: 300
    base_url: !secret nabu_casa_url
    service_name: google_say
    language: 'en-uk'

# Google Assistant integration via Dialogflow
dialogflow:

intent_script:

###################### Devices / Platforms ######################

mqtt:
  discovery: true
  discovery_prefix: mqtt_ha

# https://www.home-assistant.io/integrations/webostv
webostv:
  name: Guest Room LG TV
  host: !secret webostv_host_ip

http:
  server_port: 8123
  ip_ban_enabled: true
  login_attempts_threshold: 5
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  
sonoff:
  username: !secret sonoff_username  # also used in ourgroceries
  password: !secret sonoff_password
  mode: local
#  reload: always # update device list every time HA starts

 
#ourgroceries:
#  username: !secret sonoff_username
#  password: !secret our_groceries_password

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  ssl: false

