
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  ### The following installs all package files
  packages: !include_dir_named packages
  ### The following installs all customizions 
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  

updater:
  include_used_components: true
  
# Activate CustomUI https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/activating.md
customizer:
  custom_ui: local
  columns: [350, 700, 1050, 1400, 1850, 2100]

frontend:
  themes: !include_dir_merge_named themes

python_script:
          
switch: !include switches.yaml
#light: !include light_switch.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
device_tracker: !include device_tracker.yaml

logger:
  default: warn
  logs:
    homeassistant.components.device_tracker: debug
    #homeassistant.components.switch.template: debug
    #homeassistant.components.switch.command_line: debug
    #custom_components.wiser: debug
    #homeassistant.components.device_tracker
    #custom_components.plex_assistant: debug
    #homeassistant.components.plex: debug
    #plexapi: debug
    #miflora: debug
    #btlewrap: debug
    #bluepy: debug
    
# https://www.home-assistant.io/integrations/recorder/
recorder:
  purge_keep_days: 5
  exclude:
    domains:
    - media_player
    entities:
    - sun.sun # Don't record sun data  
    - timer.hall_light
    - remote.harmony_lounge
    - remote.harmony_bedroom
    - remote.harmony_kitchen
    - switch.harmony_lounge_tv
    - switch.harmony_lounge_bluray
    - switch.harmony_lounge_iplayer
    - switch.harmony_lounge_cast
    - switch.harmony_bedroom_tv
    - switch.harmony_bedroom_audio_cast
    - switch.harmony_bedroom_youview
    - sensor.wiser_itrv_bedroom
    - sensor.wiser_itrv_kitchen
    - sensor.wiser_itrv_guest_room
    - sensor.wiser_itrv_lounge
    - sensor.wiser_itrv_lounge_2
    - sensor.wiser_itrv_upstairs
    - sensor.wiser_itrv_upstairs_2
    - sensor.wiser_operation_mode
    - sensor.wiser_cloud_status
    - sensor.wiser_heathub
    - sensor.wiser_roomstat_upstairs
    - sensor.wiser_roomstat_lounge
    - switch.wiser_comfort_mode
    - switch.wiser_eco_mode
    - switch.wiser_valve_protection
    - switch.wiser_away_mode_affects_hot_water
    - switch.wiser_away_mode

# Text to speech via Google Translate
tts:
  - platform: google_translate
    cache: true
    #cache_dir: /tmp/tts
    time_memory: 300
    base_url: !secret nabu_casa_url
    service_name: google_say
    language: 'en-uk'

# Google Assistant integration via Dialogflow
dialogflow:

intent_script:

###################### Devices / Platforms ######################


# https://www.home-assistant.io/integrations/webostv
webostv:
  name: Guest Room LG TV
  host: !secret webostv_host

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

mqtt:
  broker: a0d7b954-mqtt
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant
#  discovery: true
#  discovery_prefix: homeassistant
  
sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  api_region: eu
  entity_prefix: true
  debug: false


  
           

