velux_upstairs_blinds:
  name: Upstairs Blinds
  entities:
  - cover.velux_north_bedroom_blind
  - cover.velux_south_bedroom_blind
  - cover.velux_north_study_blind
  - cover.velux_south_study_blind

lounge_lights:
  name: Lounge Lights
  entities:
  - switch.s4_fairy_lights
  - light.led_lights

all_lights:
  name: Lights
  entities:
  - switch.s3_hall_light
  - switch.s4_fairy_lights
  - switch.s6_upstairs_light
  - switch.s7_tree_lights
  - light.led_lights
  - light.led_hall
  - light.upstairs_colour_light

all_switches:
  name: Switch
  entities:
  - switch.s1_amplifier
  - switch.s2_bosch_battery_charger
  - switch.s5_study_computer
  - switch.ensuite_fan
  - switch.bathroom_fan
  - switch.kitchen_amp

upstairs_downstairs_leds:
  name: 'Upstairs / Lounge LED Lights'
  entities:
  - light.led_lights
  - light.upstairs_led
