velux_upstairs_blinds:
  name: Upstairs Blinds
  entities:
  - cover.velux_north_bedroom_blind
  - cover.velux_south_bedroom_blind
  - cover.velux_north_study_blind
  - cover.velux_south_study_blind

lounge_lights:
  name: Lounge Lights
  entities:
  - switch.s4_fairy_lights
  - switch.s6_rock_light
  - light.led_lights

#  switch.s7_tree_lights
#  switch.s3_hall_light

all_lights:
  name: Lights
  entities:
  - switch.s2_hall_light
  - switch.s4_fairy_lights
  - switch.s6_rock_light
  - light.led_lights  
  - light.led_hall
  - light.upstairs_led
  - light.upstairs_colour_light

all_switches:
  name: Switch
  entities:
  - switch.s1_amplifier
  - switch.s3_spare_socket
  - switch.s5_study_computer
  - light.ensuite_fan
  - switch.sonoff_bathroom_fan
  - switch.kitchen_amp
