- id: '1596191472541'
  name: Hot day WFH
  entities:
    cover.velux_north_bedroom_window:
      current_position: 30
      friendly_name: North Bedroom Window
      icon: mdi:window-closed
      state: open
      supported_features: 7
    cover.velux_north_study_window:
      current_position: 30
      friendly_name: North Study Window
      icon: mdi:window-closed
      state: open
      supported_features: 7
    cover.velux_south_bedroom_blind:
      current_position: 20
      friendly_name: South Bedroom Blind
      icon: mdi:window-shutter
      state: open
      supported_features: 7
    cover.velux_south_bedroom_window:
      current_position: 100
      friendly_name: South Bedroom Window
      icon: mdi:window-closed
      state: open
      supported_features: 7
    cover.velux_south_study_blind:
      current_position: 0
      friendly_name: South Study Blind
      icon: mdi:window-shutter
      state: closed
      supported_features: 7
    cover.velux_south_study_window:
      current_position: 50
      friendly_name: South Study Window
      icon: mdi:window-closed
      state: open
      supported_features: 7
