# https://www.home-assistant.io/integrations/darksky
- platform: darksky
  name: Cubitt Town
  api_key: !secret dark_sky_apikey
  latitude:  51.4969 # Cubitt Town Sensor
  longitude: -0.0087 # Cubitt Town Sensor
  scan_interval:
    minutes: 10
  units: si
  monitored_conditions:
  - summary
  - icon
  - precip_probability
  - precip_intensity
  - temperature
  - cloud_cover
  - visibility
  - uv_index
  - moon_phase
  - sunrise_time
  - sunset_time
  - alerts
  - humidity
  - wind_speed
  - wind_bearing
  - pressure
  - ozone
  
# https://waqi.info/
- platform: waqi
  token: !secret waqi_api_key
  locations: 
  - greenwich
  
- platform: template
  sensors:
    total_consumption:
      friendly_name: Total Consumption
      device_class: power
      unit_of_measurement: kWh
      icon_template: mdi:power-settings
      value_template: >-
        {{ 
          (states('sensor.s1_consumption') | float) + 
          (states('sensor.s2_consumption') | float) +
          (states('sensor.s3_consumption') | float) +
          (states('sensor.s4_consumption') | float) +
          (states('sensor.s5_consumption') | float) +
          (states('sensor.s6_consumption') | float) +
          (states('sensor.s7_consumption') | float) 
        }}

