- platform: template
  switches:
    working_from_home:
      friendly_name: WFH
      value_template: >-
        {{ 
          is_state('cover.velux_south_study_blind', 'closed') 
            and is_state('switch.s5_study_computer', 'on')
            and is_state('switch.s6_work_laptop', 'on')
        }}
      icon_template: >-
          {% if is_state('cover.velux_south_study_blind', 'closed') %}
            mdi:briefcase
          {% else %}
            mdi:briefcase-outline
          {% endif %}
      turn_on:
        service: script.working_from_home_start
      turn_off:    
        service: script.working_from_home_end
    

